### ISSUE TITLE
Improvements at getBestReceiver() function

### ISSUE THREAD

**Issue by zsmn** [MaracatronicsRobotics/Armorial-Suassuna-Legacy#31]
Actually the attacker behaviour is choosing the best receiver based at the distance to them. 
Making an improvement to look for more parameters may be a nice try, possibiliting that the attacker (while in poss of ball) make a pass to the best receiver (based on angulation to goal, distance to goal, etc.)

**Comment by zsmn** [comment]
Done at c7e5b09fc295f7f149a004a50cf6dfa32d8715ee

**Comment by Lucasfigueiras** [comment]
Now the attacker chooses the best reciever based on the size of the biggest free angle each have in relation to the goal
