### ISSUE TITLE
Create an function that defenders can choose an attack player to make a pass

### ISSUE THREAD

**Issue by zsmn** [MaracatronicsRobotics/Armorial-Suassuna-Legacy#35]
Actually our goalkeeper and barriers are making takeouts aiming to their goal, possibly losing the ball possession with this process. This function will make our team, at an successful takeout, make an powerful counterattack.

**Comment by Lucasfigueiras** [comment]
Now the defenders choose the attacker that has it's nearest opponent the furthest from itself

**Comment by zsmn** [comment]
Solved at 4ee21df06da71b9de352c20ffa74c866231d53e8
