### ISSUE TITLE
Attacker must push the ball to a better place in relation to goal and receivers

### ISSUE THREAD

**Issue by pedrojlsilva** [MaracatronicsRobotics/Armorial-Suassuna-Legacy#48]

**Comment by zsmn** [comment]
With path planning avoiding and the chipkick this is (probably) not an problem. The attacker will try to avoid any enemy on it's front, carrying the ball with him, or, in the worst case, will try tho make an chipkick (that probably will overhead the enemy).
If needed, I'll reopen this issue and work on.
