### ISSUE TITLE
test with many available teams

### ISSUE THREAD

**Issue by pedrojlsilva** [MaracatronicsRobotics/Armorial-Suassuna-Legacy#68]
- RoboIME
- RoboCIn
- Warthog Robotics
- Roboteam Twente (Low priority)

**Comment by zsmn** [comment]
Tested #66 with RoboCIn, Warthog and our own AI, it's working better than the older one.

**Comment by zsmn** [comment]
Tested #70 with Warthog ('cause they have an better marking) and noticed more ball possession.

**Comment by zsmn** [comment]
Tested 10304cf, 8521e51700ba6fe3e415afbaf59ebc10a75e4ef6 and 67b343db19ab57b68b9caf075b086c148112055d with Warthog and noticed higher improvements at velocity when approaching to the ball (for marking behaviours) and minor bug fixes that are noticed by any gameplay.
