### ISSUE TITLE
RobotStatus

### ISSUE THREAD

**Issue by BrenoOR** [MaracatronicsRobotics/Armorial-Suassuna-Legacy#94]
RobotStatus falha no commit `7b5cbd3c066bfa099976e50c04c01fcb3f865156` da branch `player`.
Retornando o seguinte:
[Execução](https://drive.google.com/file/d/1fOCcP4D-bcQGfsEXZsSkTjtw3yEQXVQM/view?usp=sharing)
[BackTrace](https://drive.google.com/file/d/1rdYjJzLhO9JMh7QTe1QOIqGU02Qz4MYP/view?usp=sharing)
O problema acontece no momento em que se tenta criar um objeto do tipo Robô através do Utils.

**Comment by zsmn** [comment]
https://github.com/MaracatronicsRobotics/Armorial-Suassuna/commit/7b5cbd3c066bfa099976e50c04c01fcb3f865156

**Comment by zsmn** [comment]
https://github.com/MaracatronicsRobotics/Armorial-Suassuna/blob/7b5cbd3c066bfa099976e50c04c01fcb3f865156/src/utils/utils.cpp#L211-L223

Nessa função de criação do `getRobotStatusObject` o ideal é que tu não aloque o `&robotIdentifier` e sim aloque um ponteiro propriamente porque a variável `robotIdentifier` é apagada logo após o fim do escopo e o ponteiro não.
